### ISSUE TITLE
Jython is still in development ?

### ISSUE THREAD

**Issue by nenodias** [jython/jython3#37] opened 2018-05-11 14:40 UTC
I found a mercurial repository https://hg.python.org/jython/
The git repository is not updated?

**Comment by Stewori** [comment] 2018-05-11 16:55
The Jython 2.7 git repository is a mirror of the repository you denoted. We push to the mercurial repo, which is the official code base and a script frequently mirrors changes to https://github.com/jythontools/jython. Following CPython's path of moving the codebase entirely to github is a todo.

Referring to your headline question, that seems to be a duplicate of https://github.com/jython/jython3/issues/36, where the reasons are explained, i.e. there is currently no active funding of Jython and devs can only spend their personal time on the project. That is apparently not enough to yield significant boosts, but at least a release of Jython 2.7.2 is upcoming. Progress on that is currently most visible on http://bugs.jython.org.

**Comment by jeff5** [comment] 2018-05-11 18:06
This one is a fork reflecting an attempt to move  Python 3. It is stalled because it is unclear how to move forward from here.

**Closed** 2018-05-11 18:48 UTC

**Comment by Chris-YBS** [comment] 2019-12-12 14:02
Given that Python 2 is being deprecated at the [ends](https://pythonclock.org/) at the end of the year, what is the progress on Jython 3?

**Comment by jeff5** [comment] 2022-01-29 20:33
I don't know. If you want pip to work with Jython, you could ask pip to mend pip.

I'm pretty sure a Jython 3 is the long-term answer.
https://github.com/jython/jython3/blob/master/README.md

**Comment by Stewori** [comment] 2022-01-29 23:44
Did pip also stop working with CPython 2.7? Is this a pip issue or a PyPI issue?

**Comment by stuaxo** [comment] 2022-01-31 09:55
It looks like pip < version 21 should work on CPython 2.7.

https://stackoverflow.com/a/54915827/62709

**Comment by jeff5** [comment] 2022-01-31 23:44
I'm being unfair to pip. See #97 for what I learned..
